#!/bin/bash

# To mark config files that have been updated
MARKER="(: MARKER :)"
CURRENT_PATH=$(cd -- "$(dirname -- "$0")" && pwd)

# log functions
print_info() { echo -e "[INFO] $1"; }
print_warn() { echo -e "[WARNING] $1"; }
print_error() { echo -e "[ERROR] $1"; }


###################################
# bash
###################################
# Import bashrc string
import_bashrc='
# Import .bashrc from config.desktop
if [ -f "$CURRENT_PATH/.bashrc" ]; then
	. "$CURRENT_PATH/.bashrc"
fi'


# Import bash_profile string
import_bash_profile='
# Import .bash_profile from config.desktop (: MARKER :)
if [ -f "$CURRENT_PATH/.bash_profile" ]; then
	. "$CURRENT_PATH/.bash_profile"
fi'

ensure_dir() {
	if [ ! -d "$1" ]; then
		mkdir -p "$1"
	fi
}

link_path() {
	local source_path="$1"
	local target_path="$2"

	if [ -L "$target_path" ]; then
		if [ "$(readlink -f "$target_path")" = "$(readlink -f "$source_path")" ]; then
			print_warn "$target_path already links to $source_path"
			return 0
		fi
		print_warn "Skipping $target_path because it links somewhere else"
		return 0
	fi

	if [ -e "$target_path" ]; then
		print_warn "Skipping $target_path because a file already exists there"
		return 0
	fi

	ln -s "$source_path" "$target_path"
}


config_bash(){
	# Update or link .bashrc
	print_info "Processing .bashrc ..."


	if [ -f "$HOME/.bashrc" ]; then
		grep "$MARKER" $HOME/.bashrc > /dev/null
		if [ $? -ne 0 ]; then
			print_info "Adding CURRENT_PATH env"
			echo >> "$HOME/.bashrc"
			echo "CURRENT_PATH=$CURRENT_PATH # (: MARKER :)" >> "$HOME/.bashrc"

			#echo >> "$HOME/.bashrc"
			print_info "Adding $CURRENT_PATH/.bashrc ..."
			echo "$import_bashrc" >> "$HOME/.bashrc"
		fi
	else
		print_info "Linking $CURRENT_PATH/.bashrc ..."
		link_path "$CURRENT_PATH/.bashrc" "$HOME/.bashrc"
	fi


	# Update or link .bash_profile
	print_info "Processing .bash_profile ..."
	if [ -f "$HOME/.bash_profile" ]; then
		grep "$MARKER" $HOME/.bash_profile > /dev/null
		if [ $? -ne 0 ]; then
			print_info "Adding CURRENT_PATH env"
			echo >> "$HOME/.bash_profile"
			echo "CURRENT_PATH=$CURRENT_PATH # (: MARKER :)" >> "$HOME/.bash_profile"

			print_info "Adding $CURRENT_PATH/.bash_profile ..."
			echo "$import_bash_profile" >> "$HOME/.bash_profile"
		fi
	else
		print_info "Linking $CURRENT_PATH/.bash_profile ..."
		link_path "$CURRENT_PATH/.bash_profile" "$HOME/.bash_profile"
	fi


	ensure_dir "$HOME/.config/bash"
	print_info "Linking bash helper ..."
	link_path "$CURRENT_PATH/.config/bash/copilot.bash" "$HOME/.config/bash/copilot.bash"
}


###################################
# lf (https://github.com/gokcehan/lf)
###################################
inst_lf_root() {
	print_info "Installing lf from Debian packages ..."
	sudo apt install -y lf
}

# Link lf config
config_lf(){
	print_info "Processing lf ..."
	link_path "$CURRENT_PATH/.config/lf" "$HOME/.config/lf"
}


###################################
# tmux (https://github.com/tmux/tmux)
###################################
inst_tmux_root(){
	print_info "Installing tmux from Debian packages ..."
	sudo apt install -y tmux
}

inst_tmux_noroot(){
	print_warn "tmux is not installed and no sudo privileges are available"
}

# Link tmux config
config_tmux(){
	print_info "Processing tmux ..."
	link_path "$CURRENT_PATH/.config/tmux/tmux.conf" "$HOME/.tmux.conf"

	if command -v tmux > /dev/null 2>&1 && [ -n "${TMUX:-}" ] && tmux display-message -p '#S' > /dev/null 2>&1; then
		tmux source-file "$HOME/.tmux.conf"
	fi
}


###################################
# Config vim
###################################
config_vim(){
	print_info "Configuring Neovim ..."
	if ! command -v git > /dev/null 2>&1; then
		print_warn "Skipping Neovim bootstrap because git is not installed"
		return 0
	fi

	if [ ! -d "$HOME/.config/nvim" ]; then
		# Check whether GitHub SSH auth is available before cloning.
		ssh -T git@github.com &> /dev/null
		local status=$?
		if [ $status -eq 1 ]; then
			git clone git@github.com:xinyu-yang/myvim.git "$HOME/.config/nvim"
		else
			git clone https://github.com/xinyu-yang/myvim.git "$HOME/.config/nvim"
		fi
	fi
	if [ -d "$HOME/.config/nvim/.git" ]; then
		git -C "$HOME/.config/nvim" pull origin
	fi

	if [ -f "$HOME/.config/nvim/setup.sh" ]; then
		/bin/bash "$HOME/.config/nvim/setup.sh"
	fi
}


###################################
# Preparations
###################################

# Create config directory
ensure_dir "$HOME/.config/"

# Test whether this user has sudo priviledge
if (sudo -v > /dev/null);
then
	print_info "Installing as root"
	IS_SUDOER=1
	POSTFIX=root
	array=(lf tmux)
else
	print_info "Installing as non-root"
	IS_SUDOER=0
	POSTFIX=noroot
	ensure_dir "$HOME/.local/bin"
	array=()
fi


# Install prerequirements
for app in ${array[*]}
do
	if command -v ${app} > /dev/null 2>&1;
	then
		print_warn "${app} exists!"
	else
		inst_${app}_${POSTFIX}
	fi
done


###################################
# MAIN
###################################
config_list=(bash tmux lf vim)

for app in ${config_list[*]}; do
	config_${app}
done
